workflows:
  # TrollStore 专用构建流程
  ios-trollstore:
    name: 构建 iOS IPA (给 TrollStore 用)
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      # 第1步: 获取 Flutter 依赖包
      - name: 第1步 - 获取依赖
        script: |
          echo "开始获取 Flutter 依赖..."
          flutter pub get
      
      # 第2步: 清理与初始化 (确保环境干净)
      - name: 第2步 - 深度清理
        script: |
          echo "开始清理旧缓存..."
          rm -rf build
          cd ios
          rm -rf Pods Podfile.lock .symlinks Flutter/Flutter.framework
      
      # 第3步: 安装 iOS 依赖
      - name: 第3步 - 安装 Pods
        script: |
          echo "开始安装 iOS 依赖..."
          cd ios
          pod install --repo-update
      
      # 第4步: 编译 iOS 应用 (不签名，适合 TrollStore)
      - name: 第4步 - 编译应用
        script: |
          echo "开始编译 iOS 应用..."
          flutter build ios --release --no-codesign
      
      # 第5步: 强制打包成 IPA
      - name: 第5步 - 制作 IPA 压缩包
        script: |
          echo "开始制作 IPA..."
          # 获取当前绝对路径，防止路径跳转错误
          PROJECT_ROOT=$(pwd)
          APP_PATH="$PROJECT_ROOT/build/ios/iphoneos/Runner.app"
          PAYLOAD_PATH="$PROJECT_ROOT/build/ios/iphoneos/Payload"
          IPA_NAME="PureLive.ipa"

          # 检查编译产物是否存在
          if [ ! -d "$APP_PATH" ]; then
            echo "❌ 错误: 找不到 Runner.app，编译可能失败了。"
            exit 1
          fi

          # 创建 Payload 结构
          cd "$PROJECT_ROOT/build/ios/iphoneos"
          mkdir -p Payload
          cp -r Runner.app Payload/
          
          # 打包 IPA 到项目根目录
          zip -r "$PROJECT_ROOT/$IPA_NAME" Payload
          
          echo "✅ IPA 打包完成!"
          cd "$PROJECT_ROOT"
          ls -lh "$IPA_NAME"
    
    # 保存生成的 IPA 文件
    artifacts:
      - "*.ipa"
    
    publishing:
      email:
        recipients:
          - your-email@example.com  # 记得改写成你的邮箱
        notify:
          success: true
          failure: true
