workflows:
  # 诊断构建 - 找出问题所在
  ios-diagnostic:
    name: iOS 诊断构建
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      # 步骤 1: 检查环境
      - name: 步骤1 - 检查环境
        script: |
          echo "========================================="
          echo "环境信息检查"
          echo "========================================="
          echo "Flutter 版本:"
          flutter --version
          echo ""
          echo "CocoaPods 版本:"
          pod --version
          echo ""
          echo "Xcode 版本:"
          xcodebuild -version
          echo ""
          echo "Ruby 版本:"
          ruby --version
          echo ""
          echo "当前目录:"
          pwd
          echo ""
          echo "文件列表:"
          ls -la
          echo "========================================="
      
      # 步骤 2: 获取依赖
      - name: 步骤2 - 获取 Flutter 依赖
        script: |
          echo "========================================="
          echo "获取 Flutter 依赖"
          echo "========================================="
          flutter pub get
          EXIT_CODE=$?
          if [ $EXIT_CODE -eq 0 ]; then
            echo "✅ Flutter 依赖获取成功"
          else
            echo "❌ Flutter 依赖获取失败,退出码: $EXIT_CODE"
            exit 1
          fi
          echo "========================================="
      
      # 步骤 3: 检查 iOS 目录
      - name: 步骤3 - 检查 iOS 配置
        script: |
          echo "========================================="
          echo "检查 iOS 目录和配置"
          echo "========================================="
          
          if [ -d "ios" ]; then
            echo "✅ ios 目录存在"
            echo ""
            echo "iOS 目录内容:"
            ls -la ios/
            echo ""
            
            if [ -f "ios/Podfile" ]; then
              echo "✅ Podfile 存在"
              echo ""
              echo "Podfile 内容:"
              cat ios/Podfile
            else
              echo "❌ Podfile 不存在"
            fi
            
            echo ""
            if [ -f "ios/Runner.xcodeproj/project.pbxproj" ]; then
              echo "✅ Xcode 项目文件存在"
            else
              echo "❌ Xcode 项目文件不存在"
            fi
          else
            echo "❌ ios 目录不存在!"
            exit 1
          fi
          echo "========================================="
      
      # 步骤 4: 清理缓存
      - name: 步骤4 - 清理 CocoaPods 缓存
        script: |
          echo "========================================="
          echo "清理 CocoaPods 缓存"
          echo "========================================="
          cd ios
          
          echo "删除 Pods..."
          rm -rf Pods
          
          echo "删除 Podfile.lock..."
          rm -rf Podfile.lock
          
          echo "清理全局缓存..."
          rm -rf ~/Library/Caches/CocoaPods
          
          echo "清理 Flutter 链接..."
          rm -rf .symlinks
          rm -rf Flutter/Flutter.framework
          rm -rf Flutter/Flutter.podspec
          
          cd ..
          echo "✅ 缓存清理完成"
          echo "========================================="
      
      # 步骤 5: 更新 CocoaPods 仓库
      - name: 步骤5 - 更新 CocoaPods 仓库
        script: |
          echo "========================================="
          echo "更新 CocoaPods 仓库"
          echo "========================================="
          cd ios
          
          echo "开始更新 CocoaPods specs..."
          pod repo update
          EXIT_CODE=$?
          
          if [ $EXIT_CODE -eq 0 ]; then
            echo "✅ CocoaPods 仓库更新成功"
          else
            echo "❌ CocoaPods 仓库更新失败,退出码: $EXIT_CODE"
            exit 1
          fi
          
          cd ..
          echo "========================================="
      
      # 步骤 6: 安装 CocoaPods 依赖
      - name: 步骤6 - 安装 iOS 依赖
        script: |
          echo "========================================="
          echo "安装 CocoaPods 依赖"
          echo "========================================="
          cd ios
          
          echo "开始安装 Pods (详细模式)..."
          pod install --repo-update --verbose 2>&1 | tee pod_install.log
          EXIT_CODE=${PIPESTATUS[0]}
          
          echo ""
          if [ $EXIT_CODE -eq 0 ]; then
            echo "✅ Pods 安装成功"
            echo ""
            echo "已安装的 Pods:"
            ls -la Pods/ | head -30
          else
            echo "❌ Pods 安装失败,退出码: $EXIT_CODE"
            echo ""
            echo "错误日志最后 100 行:"
            tail -100 pod_install.log
            exit 1
          fi
          
          cd ..
          echo "========================================="
      
      # 步骤 7: 编译 iOS 应用
      - name: 步骤7 - 编译 iOS 应用
        script: |
          echo "========================================="
          echo "编译 iOS 应用"
          echo "========================================="
          
          echo "开始编译 (详细模式)..."
          flutter build ios --release --no-codesign -v 2>&1 | tee flutter_build.log
          EXIT_CODE=${PIPESTATUS[0]}
          
          echo ""
          if [ $EXIT_CODE -eq 0 ]; then
            echo "✅ 编译成功"
          else
            echo "❌ 编译失败,退出码: $EXIT_CODE"
            echo ""
            echo "编译日志最后 200 行:"
            tail -200 flutter_build.log
            echo ""
            echo "查找错误信息:"
            grep -i "error" flutter_build.log | tail -20
            exit 1
          fi
          
          echo ""
          echo "检查编译产物..."
          if [ -d "build/ios/iphoneos/Runner.app" ]; then
            echo "✅ Runner.app 已生成"
            echo ""
            echo "Runner.app 内容:"
            ls -lh build/ios/iphoneos/Runner.app
          else
            echo "❌ Runner.app 未生成"
            echo ""
            echo "build 目录结构:"
            find build -type d -maxdepth 4 2>/dev/null || echo "build 目录不存在"
            exit 1
          fi
          echo "========================================="
      
      # 步骤 8: 打包 IPA
      - name: 步骤8 - 打包 IPA
        script: |
          echo "========================================="
          echo "打包 IPA"
          echo "========================================="
          
          # 再次检查 Runner.app
          if [ ! -d "build/ios/iphoneos/Runner.app" ]; then
            echo "❌ 错误: Runner.app 不存在,无法打包"
            exit 1
          fi
          
          echo "进入构建目录..."
          cd build/ios/iphoneos
          
          echo "创建 Payload 目录..."
          mkdir -p Payload
          
          echo "复制 Runner.app..."
          cp -r Runner.app Payload/
          
          echo "打包为 IPA..."
          zip -r PureLive-TrollStore.ipa Payload
          
          echo "移动 IPA 到根目录..."
          mv PureLive-TrollStore.ipa ../../../
          
          echo "清理 Payload..."
          rm -rf Payload
          
          echo "返回根目录..."
          cd ../../..
          
          # 验证 IPA
          if [ -f "PureLive-TrollStore.ipa" ]; then
            echo "✅ IPA 打包成功!"
            echo ""
            echo "文件信息:"
            ls -lh PureLive-TrollStore.ipa
            echo ""
            echo "IPA 内容预览:"
            unzip -l PureLive-TrollStore.ipa | head -30
          else
            echo "❌ IPA 打包失败"
            exit 1
          fi
          echo "========================================="
    
    # 保存所有重要文件
    artifacts:
      - PureLive-TrollStore.ipa
      - "*.log"
      - build/ios/iphoneos/Runner.app/**/*
    
    # 邮件通知
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
