workflows:
  ios-pure-live:
    name: iOS Pure Live (Unsigned IPA)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:  
      flutter: stable  
      xcode: latest  

    scripts:  
      - name: Flutter pub get  
        script: |
          flutter pub get  

      - name: Build iOS (no codesign)  
        script: |
          cd ios
          pod install --repo-update
          cd ..
          flutter build ios --no-codesign

      - name: Create IPA  
        script: |  
          mkdir Payload  
          cp -r build/ios/iphoneos/Runner.app Payload/  
          zip -r PureLive.ipa Payload  

    artifacts:  
      - PureLive.ipa
