workflows:
  ios-trollstore:
    name: PureLive TrollStore Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: 第1步 - 获取依赖
        script: flutter clean && flutter pub get && flutter precache --ios

      - name: 第2步 - 注入 Podfile 修复脚本
        script: |
          cd ios
          echo "post_install do |installer|" >> Podfile
          echo "  installer.pods_project.targets.each do |target|" >> Podfile
          echo "    target.build_configurations.each do |config|" >> Podfile
          echo "      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'" >> Podfile
          echo "      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'" >> Podfile
          echo "    end" >> Podfile
          echo "  end" >> Podfile
          echo "end" >> Podfile

      - name: 第3步 - 安装 Pods
        script: cd ios && pod repo update && pod install --repo-update

      - name: 第4步 - 编译应用
        script: flutter build ios --release --no-codesign

      - name: 第5步 - 打包 IPA
        script: |
          export PROJECT_ROOT=$(pwd)
          export BUILD_DIR="$PROJECT_ROOT/build/ios/iphoneos"
          cd "$BUILD_DIR"
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r "$PROJECT_ROOT/PureLive.ipa" Payload
          cd "$PROJECT_ROOT"
          ls -lh PureLive.ipa

    artifacts:
      - "*.ipa"

    publishing:
      email:
        recipients:
          - your-email@example.com
